services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: ha-dev
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ../:/workspaces/python-reverse-proxy
      - ha-config:/config
    ports:
      - "8123:8123"
    networks:
      - ha-network
    command: >
      bash -c "
        echo '🏠 Starting Home Assistant development environment...'
        
        # Create required directories
        mkdir -p /config/custom_components
        mkdir -p /config/deps
        
        # Copy our homie-proxy integration
        if [ -d '/workspaces/python-reverse-proxy/custom_components/homie_proxy' ]; then
          echo '📦 Copying homie_proxy integration...'
          cp -r /workspaces/python-reverse-proxy/custom_components/homie_proxy /config/custom_components/
          ls -la /config/custom_components/homie_proxy/
        else
          echo '⚠️  homie_proxy integration not found'
        fi
        
        # Copy Home Assistant configuration files
        echo '⚙️  Setting up configuration files...'
        cp /workspaces/python-reverse-proxy/.devcontainer/configuration.yaml /config/configuration.yaml
        cp /workspaces/python-reverse-proxy/.devcontainer/automations.yaml /config/automations.yaml
        cp /workspaces/python-reverse-proxy/.devcontainer/scenes.yaml /config/scenes.yaml
        cp /workspaces/python-reverse-proxy/.devcontainer/scripts.yaml /config/scripts.yaml
        
        # Verify configuration
        echo '🔍 Verifying Home Assistant configuration...'
        python -m homeassistant --script check_config --config /config || echo 'Configuration check failed, but continuing...'
        
        # Start Home Assistant
        echo '🚀 Starting Home Assistant...'
        exec python -m homeassistant --config /config
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/api/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  ha-config:

networks:
  ha-network:
    driver: bridge 